name: Network Configuration Pipeline

on:
  push:
    paths:
      - 'changes/**'
  pull_request:
    paths:
      - 'changes/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Render Configuration with Ansible
      run: |
        cd ansible
        for change_dir in ../changes/*/; do
          if [[ -d "$change_dir" ]]; then
            change_request=$(basename "$change_dir")
            echo "Processing change request: $change_request"
            ansible-playbook render_configs.yml -e "change_request=$change_request" -v
          fi
        done

    - name: Commit rendered configurations
      if: github.event_name == 'push'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add changes/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-render configurations from YAML templates"
          git push
        fi

    - name: Cleanup
      run: echo "Cleanup tasks after CI"

